name: Auto Release on Major Version Bump

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when a version tag is pushed (e.g., v1.0.0)

jobs:
  release:
    name: Create GitHub Release for Major Versions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare tags

      - name: Get previous tag
        id: previous_tag
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sed -n 2p)
          echo "Previous tag: $PREV_TAG"
          echo "::set-output name=previous::$PREV_TAG"

      - name: Compare major versions
        id: check_major
        run: |
          CURRENT_TAG="${{ github.ref_name }}"  # Extract current tag (e.g., v2.0.0)
          PREV_TAG="${{ steps.previous_tag.outputs.previous }}"  # Extract previous tag (e.g., v1.2.3)

          # Extract major version numbers
          CUR_MAJOR=$(echo "$CURRENT_TAG" | cut -d'.' -f1 | tr -d 'v')
          PREV_MAJOR=$(echo "$PREV_TAG" | cut -d'.' -f1 | tr -d 'v')

          echo "Current major version: $CUR_MAJOR"
          echo "Previous major version: $PREV_MAJOR"

          if [ "$CUR_MAJOR" -gt "$PREV_MAJOR" ]; then
            echo "Major version increased, proceeding with release."
            echo "release=true" >> $GITHUB_ENV
          else
            echo "No major version bump, skipping release."
            echo "release=false" >> $GITHUB_ENV
          fi

      - name: Generate Changelog
        if: ${{ env.release == 'true' }}
        run: |
          echo "## Changes in this release:" > RELEASE_NOTES.md
          git log --oneline $(git describe --tags --abbrev=0 @^)..@ >> RELEASE_NOTES.md

      - name: Create GitHub Release
        if: ${{ env.release == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          bodyFile: "RELEASE_NOTES.md"
          draft: false
          prerelease: false
