name: 'Bump Version (Deploy Key)'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.AUTO_VERSION }}  # Uses SSH instead of PAT

      - name: Bump version
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Still needed for tags?

      - name: Push changes (via SSH)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git push origin HEAD:master --tags
