name: 'Bump Version in Main'

on:
  pull_request:
    branches: [ 'main' ]
    types: [closed]

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout main'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: 'Fetch latest package.json from main'
        run: |
          git fetch origin main  # Get the latest main branch
          git checkout origin/main -- package.json  # Copy the latest package.json from main
          echo "Updated package.json from main:"
          cat package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          major-wording: 'major,breaking,overhaul,revamp'
          minor-wording: 'minor,added,feat,feature,implement,new,introduced'
          patch-wording: 'fix,bugfix,patch,workaround,secure,security,correct'
          default: 'patch'
          
          tag-prefix: 'v'
          tag-suffix: '-beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
#      - name: 'cat package.json'
#        run: cat ./package.json
#      - name: 'Output Step'
#        env:
#          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
#        run: echo "new tag $NEW_TAG"
