name: 'Bump Version in Main'

on:
  pull_request:
    types: [closed]  # Run only when the PR is merged
    branches: [ 'main' ]

jobs:
  bump-version:
    name: 'Bump Version in Main'
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes to main

    steps:
      - name: 'Checkout main'
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure we're on the latest main branch
          fetch-depth: 0  # Fetch full history to avoid issues with versioning

      - name: 'Get latest version from main'
        run: |
          git pull origin main
          echo "Current version in main: $(jq -r '.version' package.json)"

      - name: 'Bump Version'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          major-wording: 'major, breaking, overhaul, revamp'
          minor-wording: 'minor, add, added, feat, feature, implement, new, introduced'
          patch-wording: 'fix, bugfix, patch, workaround, secure, security, correct'
          default: 'patch'
          tag-prefix: 'v'
          tag-suffix: '-beta'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push Bumped Version to Main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "ci: version bump to ${{ steps.version-bump.outputs.newTag }}"
          git push origin main

      - name: 'Output new version'
        run: echo "New version in main: ${{ steps.version-bump.outputs.newTag }}"
