name: 'Bump Version'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.AUTO_VERSIONING_SECRET_KEY }}
          
      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          major-wording: 'major, breaking, overhaul, revamp'
          minor-wording: 'minor, feat, feature, implement, new, introduced'
          patch-wording: 'fix, bugfix, patch, workaround, secure, security, correct'
          default: 'patch'
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_VERSIONING_SECRET_KEY }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Push changes'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "chore: bump version to ${{ steps.version-bump.outputs.newTag }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_VERSIONING_SECRET_KEY }}
