name: 'Bump Version (Deploy Key)'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.AUTO_VERSION }}  # Uses SSH instead of PAT

      - name: Configure Git for SSH
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Bump version
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: "" # Still needed for tags?
          GIT_SSH_COMMAND: "ssh -i ${{ github.workspace }}/.ssh/id_rsa"


      - name: Push changes (SSH)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote -v  # Debug current remote
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git push origin HEAD:main --tags
